DOCKER_IMAGE_NAME ?= robert-go-monorepo/delay_app

run:
	go run ./cmd/delay_app
.PHONY: run

docker_build:
	docker build -t="$(DOCKER_IMAGE_NAME)" -f ./dockerfiles/Dockerfile.delay_app .
.PHONY: docker_build

docker_run:
	docker run --rm --name delay_app -p 8080:8080 $(DOCKER_IMAGE_NAME)
.PHONY: docker_run