FROM golang:1.23.4 AS builder
WORKDIR /app

COPY cmd ./cmd
COPY internal ./internal
COPY pkg ./pkg
COPY go.mod ./go.mod
COPY go.sum ./go.sum

RUN go mod download
RUN go build -o ./bin/main ./cmd/delay_app

FROM golang:1.23.4 AS runner
WORKDIR /app
COPY --from=builder /app/bin/main ./bin/main

EXPOSE 8080
CMD ["./bin/main"]
